# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: "python:3.8-slim"

#commands to run in the Docker container before starting each job.
before_script:
  - python --version
  - python3 -m venv .venv
  - |-
    source .venv/bin/activate \
    && \
    python3 -m pip install --upgrade pip \
    && \
    python3 install_requirements.py

# different stages in the pipeline
stages:
  - _static_analysis_

pylint:
  stage: _static_analysis_
  script:
    - |-
      source .venv/bin/activate \
      && \
      python3 -m pip install pylint \
      && \
      pylint app
